server:
  port: 8889
eureka:
  client:
    service-url:
      defaultZone: 'http://eureka1:8888/eureka/,http://eureka2:8886/eureka/'
    healthcheck:
      enabled: true
spring:
  application:
    name: 'config'
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: 'https://gitee.com/wupeigit/SpringcloudConfig'
        #  uri: 'https://github.com/FurionCS/SpringcloudConfig'
          search-paths: 'shop'
          password: '2HXXcLLMum5YVjH'
          username: 'wupeigit'
      label: master
encrypt:
 # key: '*&3loa#@9no_0*(!'
  key-store:
    location: server.jks
    password: letmein
    alias: mytestkey
    secret: changeme

#security:
#  basic:
#    enabled: true
#  user:
#    name: cs
#    password: 123456
management:
  security:
    enabled: false
